name: mocki
port: 3001
endpoints:
  - path: /random
    method: get
    behavior: random
    responses:
      - statusCode: 200
        body:
          ugensCO2: 0.35
          sidsteUgesElCO2: 0.33
        headers:
          - name: content-type
            value: application/json
      - statusCode: 200
        body:
          ugensCO2: 0.44
          sidsteUgesElCO2: 0.86
        headers:
          - name: content-type
            value: application/json
