name: mocki
port: 3001
endpoints:
  - path: /
    method: get
    responses:
      - statusCode: 200
        body:
          message: Hello from Mocki
        headers:
          - name: content-type
            value: application/json
